# R2Devops.io pipeline generation
#
# List of technologies detected in the project : html, markdown, python, yaml, 

name: R2Devops
on:
  push:
    branches: [ master, r2devops]
  pull_request:
    branches: [ master ]

jobs:
# A style guide linter widely used
  python-flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - run: python -m pip install flake8
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8

# A python formatter to help you write homogeneous code
  python-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable

  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master


